const navQuiz=document.querySelector('#navQuiz'),quizView=document.querySelector('#quizView'),quizBuilder=document.querySelector('#quizBuilder'),quizPlayer=document.querySelector('#quizPlayer'),quizResults=document.querySelector('#quizResults');
const quizPairs=document.querySelector('#quizPairs'),quizRelation=document.querySelector('#quizRelation'),quizDirection=document.querySelector('#quizDirection'),quizAnswerMode=document.querySelector('#quizAnswerMode'),quizTemplate=document.querySelector('#quizTemplate');
const quizPasteText=document.querySelector('#quizPasteText'),quizPairsPanel=document.querySelector('#quizPairsPanel'),quizPastePanel=document.querySelector('#quizPastePanel'),quizSourcePairs=document.querySelector('#quizSourcePairs'),quizSourcePaste=document.querySelector('#quizSourcePaste');
let generatedQuiz=[],quizIndex=0,quizPoints=0,quizBuffer='',quizSelected='',quizLocked=false,quizAnswers=[],quizKeyboardLanguage='ksw',quizSourceMode='pairs';

function openQuiz(){if(typeof openCalculator==='function')openCalculator('quiz');else{typeView.hidden=true;practiceView.hidden=true;gamesView.hidden=true;quizView.hidden=false;navType.classList.remove('active');navPractice.classList.remove('active');navGames.classList.remove('active');navQuiz?.classList.add('active')}if(typeof stopGame==='function')stopGame();if(typeof closeRace==='function')closeRace();quizBuilder.hidden=false;quizPlayer.hidden=true;quizResults.hidden=true;const classRoom=document.querySelector('#quizClassroom');if(classRoom)classRoom.hidden=true;window.scrollTo({top:0,behavior:'smooth'})}
if(navQuiz)navQuiz.onclick=openQuiz;
quizRelation.onchange=()=>{document.querySelector('#quizTemplateField').hidden=quizRelation.value!=='custom'};

function parseQuizPairs(){return quizPairs.value.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map((line,index)=>{const divider=line.indexOf('=');if(divider<1||divider===line.length-1)throw new Error(`Line ${index+1} needs an equals sign between the two items.`);return{term:line.slice(0,divider).trim(),answer:line.slice(divider+1).trim()}})}
function questionFor(pair,index){const relation=quizRelation.value;const reverse=quizDirection.value==='reverse';let question,answer,promptTerm;
  if(relation==='custom'){promptTerm=reverse?pair.answer:pair.term;question=quizTemplate.value.trim().replaceAll('{term}',promptTerm).replaceAll('{answer}',reverse?pair.term:pair.answer).replaceAll('{relationship}','answer');answer=reverse?pair.term:pair.answer}
  else{question=reverse?`What does “${pair.answer}” mean in English?`:`What is “${pair.term}” in ${languageName()}?`;answer=reverse?pair.term:pair.answer}
  const mode=quizAnswerMode.value==='mixed'?(index%2?'choice':'typing'):quizAnswerMode.value;return{...pair,relation,reverse,question,answer,mode,points:1}}
function setQuizSource(mode){quizSourceMode=mode==='paste'?'paste':'pairs';const paste=quizSourceMode==='paste';quizPairsPanel.hidden=paste;quizPastePanel.hidden=!paste;quizSourcePairs.classList.toggle('active',!paste);quizSourcePaste.classList.toggle('active',paste);quizSourcePairs.setAttribute('aria-selected',String(!paste));quizSourcePaste.setAttribute('aria-selected',String(paste));document.querySelector('#quizError').textContent='';document.querySelector('#quizPreview').hidden=true;generatedQuiz=[]}
quizSourcePairs.onclick=()=>setQuizSource('pairs');
quizSourcePaste.onclick=()=>setQuizSource('paste');

function stripQuizMarkdown(value){return String(value||'').replace(/\*\*/g,'').replace(/__/g,'').replace(/^\s*[-•]\s+/,'').trim()}
function parsePastedQuizText(text){const lines=String(text||'').replace(/\r/g,'').split('\n'),questions=[],answerKey=new Map();let current=null,inAnswerKey=false;
  const finish=()=>{if(!current)return;if(!current.question)throw new Error(`Question ${current.number||questions.length+1} is missing its question text.`);if(current.choices.length<2)throw new Error(`Question ${current.number||questions.length+1} needs at least two answer choices.`);questions.push(current);current=null};
  for(const raw of lines){const line=stripQuizMarkdown(raw);if(!line)continue;if(/^answer\s*key\s*:?(?:\s*)$/i.test(line)){finish();inAnswerKey=true;continue}if(inAnswerKey||/^answers?\s*:/i.test(line)){const source=line.replace(/^answers?\s*:\s*/i,'');let found=false;for(const match of source.matchAll(/(\d+)\s*[.):-]?\s*([A-H])\b/gi)){answerKey.set(Number(match[1]),match[2].toUpperCase());found=true}if(found)continue;if(inAnswerKey)continue}
    const q=line.match(/^(\d+)\s*[.)]\s*(.+)$/);if(q){finish();inAnswerKey=false;current={number:Number(q[1]),question:stripQuizMarkdown(q[2]),choices:[],choiceLetters:[],answerLetter:'',answer:'',mode:'choice',relation:'imported',reverse:false,source:'paste',points:1};continue}
    const option=line.match(/^([A-H])\s*[.)]\s*(.+)$/i);if(option&&current){const letter=option[1].toUpperCase();if(current.choiceLetters.includes(letter))throw new Error(`Question ${current.number} has more than one ${letter} choice.`);current.choiceLetters.push(letter);current.choices.push(stripQuizMarkdown(option[2]));continue}
    const answer=line.match(/^(?:answer|correct(?:\s+answer)?)\s*[:\-]\s*([A-H])\b/i);if(answer&&current){current.answerLetter=answer[1].toUpperCase();continue}
    if(current&&current.choices.length===0)current.question+=' '+line;
  }
  finish();if(!questions.length)throw new Error('No quiz questions found. Start each question with a number such as 1. and each choice with A., B., C., D.');
  questions.forEach((item,index)=>{const letter=item.answerLetter||answerKey.get(item.number)||'';if(letter){const choiceIndex=item.choiceLetters.indexOf(letter);if(choiceIndex<0)throw new Error(`Question ${item.number||index+1} says Answer: ${letter}, but that choice was not found.`);item.correctIndex=choiceIndex;item.answer=item.choices[choiceIndex];item.answerLetter=letter}else item.correctIndex=-1});return questions}

function generateQuestions(){quizSourceMode='pairs';const error=document.querySelector('#quizError');error.textContent='';try{const pairs=parseQuizPairs();if(!pairs.length)throw new Error('Add at least one word and answer pair.');if(quizRelation.value==='custom'&&!quizTemplate.value.includes('{term}'))throw new Error('The custom template must include {term}.');generatedQuiz=pairs.map(questionFor);renderQuizPreview()}catch(err){generatedQuiz=[];document.querySelector('#quizPreview').hidden=true;error.textContent=err.message}}
function importQuizText(){const error=document.querySelector('#quizError'),status=document.querySelector('#quizImportStatus');error.textContent='';status.textContent='';try{generatedQuiz=parsePastedQuizText(quizPasteText.value);quizSourceMode='paste';renderQuizPreview();const missing=generatedQuiz.filter(item=>!item.answer).length;status.textContent=missing?`${generatedQuiz.length} questions imported • choose ${missing} correct ${missing===1?'answer':'answers'}`:`${generatedQuiz.length} questions imported • answer key ready`;return true}catch(err){generatedQuiz=[];document.querySelector('#quizPreview').hidden=true;error.textContent=err.message;return false}}
document.querySelector('#importQuizText').onclick=importQuizText;
document.querySelector('#clearQuizText').onclick=()=>{quizPasteText.value='';generatedQuiz=[];document.querySelector('#quizPreview').hidden=true;document.querySelector('#quizError').textContent='';document.querySelector('#quizImportStatus').textContent='';quizPasteText.focus()};

function quizEnsureReady(){if(!generatedQuiz.length){if(quizSourceMode==='paste'){if(!importQuizText())return false}else{generateQuestions();if(!generatedQuiz.length)return false}}const missing=generatedQuiz.filter(item=>Array.isArray(item.choices)&&item.choices.length&&!item.answer);if(missing.length){document.querySelector('#quizError').textContent=`Choose the correct answer for ${missing.length} imported ${missing.length===1?'question':'questions'} before continuing.`;document.querySelector('#quizPreview').hidden=false;return false}document.querySelector('#quizError').textContent='';return true}
function choicesForQuizItem(item){if(Array.isArray(item.choices)&&item.choices.length)return [...item.choices];const pool=generatedQuiz.map(other=>other.answer).filter((answer,index,array)=>answer&&array.indexOf(answer)===index);return [item.answer,...pool.filter(answer=>answer!==item.answer).slice(0,3)]}
function quizItemPoints(item){const value=Math.round(Number(item?.points));return Number.isFinite(value)?Math.min(100,Math.max(0,value)):1}
function quizTotalPoints(){return generatedQuiz.reduce((total,item)=>total+quizItemPoints(item),0)}
function updateQuizPreviewCount(){const count=document.querySelector('#quizPreviewCount');if(!count)return;const imported=generatedQuiz.filter(item=>Array.isArray(item.choices)&&item.source==='paste'),missing=imported.filter(item=>!item.answer).length;count.textContent=`${generatedQuiz.length} ${generatedQuiz.length===1?'question':'questions'} • ${quizTotalPoints()} total ${quizTotalPoints()===1?'point':'points'}${imported.length?` • ${missing?`${missing} need ${missing===1?'an answer':'answers'}`:'answer key ready'}`:''}`;count.classList.toggle('quiz-preview-ready',!!imported.length&&!missing);count.classList.toggle('quiz-preview-needs-answer',!!missing)}
function quizPointsControl(item,index){item.points=quizItemPoints(item);return`<label class="quiz-question-points">Points <input type="number" min="0" max="100" step="1" inputmode="numeric" value="${item.points}" data-quiz-points="${index}" aria-label="Points for question ${index+1}"></label>`}
function applyQuizAllPoints(){const input=document.querySelector('#quizAllPoints');if(!input||!generatedQuiz.length)return;const value=Math.min(100,Math.max(0,Math.round(Number(input.value)||0)));input.value=String(value);generatedQuiz.forEach(item=>{item.points=value});renderQuizPreview();showToast(`Set all ${generatedQuiz.length} ${generatedQuiz.length===1?'question':'questions'} to ${value} ${value===1?'point':'points'} each`)}
function exportGoogleQuiz(){if(!quizEnsureReady())return;const questions=generatedQuiz.map(item=>({question:item.question,answer:item.answer,choices:choicesForQuizItem(item),points:quizItemPoints(item)}));const script=`function createGLNKarenQuiz() {\n  const questions = ${JSON.stringify(questions)};\n  const form = FormApp.create('GLN Karen Quiz').setIsQuiz(true);\n  questions.forEach((question, index) => {\n    const item = form.addMultipleChoiceItem();\n    const choices = [...new Set(question.choices)].map(choice => item.createChoice(choice, choice === question.answer));\n    item.setTitle((index + 1) + '. ' + question.question).setChoices(choices).setPoints(question.points).setRequired(true);\n  });\n  Logger.log('Total points: ' + questions.reduce((sum, question) => sum + question.points, 0));\n  Logger.log('Edit URL: ' + form.getEditUrl());\n  Logger.log('Student URL: ' + form.getPublishedUrl());\n}`;const blob=new Blob([script],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='GLN-Karen-Google-Quiz.gs';link.click();URL.revokeObjectURL(url);showToast(`Google Forms quiz script downloaded • ${quizTotalPoints()} total points`)}
document.querySelector('#exportGoogleQuiz').onclick=exportGoogleQuiz;
function renderQuizPreview(){const preview=document.querySelector('#quizPreview'),list=document.querySelector('#quizPreviewList');preview.hidden=false;updateQuizPreviewCount();list.innerHTML=generatedQuiz.map((item,index)=>{const points=quizPointsControl(item,index);if(Array.isArray(item.choices)&&item.source==='paste'){const buttons=item.choices.map((choice,choiceIndex)=>{const letter=item.choiceLetters?.[choiceIndex]||String.fromCharCode(65+choiceIndex),selected=item.answer&&normalizeQuizAnswer(choice)===normalizeQuizAnswer(item.answer);return`<button type="button" class="quiz-import-choice${selected?' is-answer':''}" data-import-question="${index}" data-import-answer="${choiceIndex}"><b>${escapeQuizHtml(letter)}</b><span>${escapeQuizHtml(choice)}</span></button>`}).join('');return`<li class="quiz-import-question${item.answer?'':' needs-answer'}"><div class="quiz-import-question-head"><strong>${escapeQuizHtml(item.question)}</strong>${points}</div><span class="quiz-import-answer-title">${item.answer?'Correct answer selected':'Choose the correct answer'}</span><div class="quiz-import-choices">${buttons}</div></li>`}return`<li><div class="quiz-import-question-head"><span>${escapeQuizHtml(item.question)} <small>Answer: ${escapeQuizHtml(item.answer)}</small></span>${points}</div></li>`}).join('')}
function escapeQuizHtml(value){const box=document.createElement('div');box.textContent=value??'';return box.innerHTML}
document.querySelector('#quizPreviewList').onclick=event=>{const button=event.target.closest('[data-import-question][data-import-answer]');if(!button)return;const q=Number(button.dataset.importQuestion),a=Number(button.dataset.importAnswer),item=generatedQuiz[q];if(!item||!Array.isArray(item.choices)||!item.choices[a])return;item.correctIndex=a;item.answer=item.choices[a];item.answerLetter=item.choiceLetters?.[a]||String.fromCharCode(65+a);renderQuizPreview();const missing=generatedQuiz.filter(entry=>Array.isArray(entry.choices)&&entry.source==='paste'&&!entry.answer).length;document.querySelector('#quizImportStatus').textContent=missing?`${generatedQuiz.length} questions imported • choose ${missing} correct ${missing===1?'answer':'answers'}`:`${generatedQuiz.length} questions imported • answer key ready`};
document.querySelector('#quizPreviewList').addEventListener('input',event=>{const input=event.target.closest('[data-quiz-points]');if(!input)return;const index=Number(input.dataset.quizPoints),item=generatedQuiz[index];if(!item)return;const value=Math.min(100,Math.max(0,Math.round(Number(input.value)||0)));item.points=value;input.value=String(value);updateQuizPreviewCount()});
document.querySelector('#applyQuizAllPoints').addEventListener('click',applyQuizAllPoints);
document.querySelector('#quizAllPoints').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();applyQuizAllPoints()}});
document.querySelector('#generateQuiz').onclick=generateQuestions;

function startQuiz(){if(!quizEnsureReady())return;quizRestoreLocalHandlers();quizIndex=0;quizPoints=0;quizAnswers=[];quizBuilder.hidden=true;quizResults.hidden=true;quizPlayer.hidden=false;showQuizQuestion();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelector('#startQuiz').onclick=startQuiz;
function currentQuiz(){return generatedQuiz[quizIndex]}
function showQuizQuestion(){const item=currentQuiz();quizBuffer='';quizSelected='';quizLocked=false;quizKeyboardLanguage=quizDefaultKeyboardLanguage(item);document.querySelector('#quizProgress').textContent=`Question ${quizIndex+1} of ${generatedQuiz.length}`;document.querySelector('#quizScore').textContent=`Score: ${quizPoints}`;document.querySelector('#quizProgressBar').style.width=`${quizIndex/generatedQuiz.length*100}%`;document.querySelector('#quizQuestion').textContent=item.question;document.querySelector('#quizType').textContent=item.mode==='choice'?'CHOOSE THE BEST ANSWER':'TYPE YOUR ANSWER';const typed=document.querySelector('#quizTypedAnswer');typed.textContent='';typed.className='quiz-typed-answer';typed.lang=quizAnswerLanguage(item);typed.hidden=item.mode==='choice';const choices=document.querySelector('#quizChoices');choices.hidden=item.mode!=='choice';document.querySelector('#quizFeedback').textContent='';document.querySelector('#quizFeedback').className='quiz-feedback';document.querySelector('#checkQuizAnswer').hidden=false;document.querySelector('#nextQuizQuestion').hidden=true;if(item.mode==='choice')renderQuizChoices();renderQuizKeyboard();if(item.mode==='typing')typed.focus()}
function quizDefaultKeyboardLanguage(item){if(!item||!hasMyanmar(item.answer))return'en';return typingLanguage==='pwo'?'pwo':'ksw'}
function quizKeyboardTag(language=quizKeyboardLanguage){return language==='en'?'en':language==='pwo'?'kjp':'ksw'}
function quizAnswerLanguage(item){return hasMyanmar(item.answer)?quizKeyboardTag():'en'}
function hasMyanmar(value){return /[\u1000-\u109f\ua9e0-\ua9ff\uaa60-\uaa7f]/iu.test(value)}
function shuffled(values){const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function renderQuizChoices(){const item=currentQuiz(),pool=generatedQuiz.map(question=>question.answer).filter((answer,index,array)=>array.indexOf(answer)===index),choices=Array.isArray(item.choices)&&item.choices.length?[...item.choices]:shuffled([item.answer,...shuffled(pool.filter(answer=>answer!==item.answer)).slice(0,3)]);const box=document.querySelector('#quizChoices');box.innerHTML='';choices.forEach(value=>{const button=document.createElement('button');button.type='button';button.className='quiz-choice';button.textContent=value;button.onclick=()=>{if(quizLocked)return;quizSelected=value;box.querySelectorAll('.quiz-choice').forEach(choice=>choice.classList.toggle('selected',choice===button))};box.appendChild(button)})}
function normalizeQuizAnswer(value){return value.normalize('NFC').trim().replace(/\s+/g,' ').toLocaleLowerCase()}
function submitQuizAnswer(){const inClassroom=typeof quizClassRole!=='undefined'&&quizClassRole==='student'&&quizClassCode&&typeof checkClassQuizAnswer==='function';if(inClassroom)checkClassQuizAnswer();else checkQuiz()}
function checkQuiz(){if(quizLocked)return;const item=currentQuiz(),response=item.mode==='choice'?quizSelected:quizBuffer;if(!response){document.querySelector('#quizFeedback').textContent=item.mode==='choice'?'Choose an answer first.':'Type an answer first.';return}quizLocked=true;const correct=normalizeQuizAnswer(response)===normalizeQuizAnswer(item.answer);if(correct)quizPoints++;quizAnswers.push({question:item.question,response,answer:item.answer,correct});const feedback=document.querySelector('#quizFeedback');feedback.textContent=correct?'Correct!':`Correct answer: ${item.answer}`;feedback.className=`quiz-feedback ${correct?'correct':'wrong'}`;if(item.mode==='typing'){document.querySelector('#quizTypedAnswer').classList.add(correct?'correct':'wrong')}else{document.querySelectorAll('.quiz-choice').forEach(choice=>{if(normalizeQuizAnswer(choice.textContent)===normalizeQuizAnswer(item.answer))choice.classList.add('correct');else if(choice.classList.contains('selected'))choice.classList.add('wrong')})}document.querySelector('#quizScore').textContent=`Score: ${quizPoints}`;document.querySelector('#checkQuizAnswer').hidden=true;document.querySelector('#nextQuizQuestion').hidden=false;document.querySelector('#nextQuizQuestion').textContent=quizIndex===generatedQuiz.length-1?'See results →':'Next question →'}
function nextLocalQuizQuestion(){if(quizIndex<generatedQuiz.length-1){quizIndex++;showQuizQuestion()}else finishQuiz()}
function editLocalQuiz(){quizPlayer.hidden=true;quizBuilder.hidden=false;window.scrollTo({top:0,behavior:'smooth'})}
function quizRestoreLocalHandlers(){const check=document.querySelector('#checkQuizAnswer'),next=document.querySelector('#nextQuizQuestion'),edit=document.querySelector('#editQuiz');check.onclick=checkQuiz;next.onclick=nextLocalQuizQuestion;edit.textContent='← Edit quiz';edit.onclick=editLocalQuiz}
document.querySelector('#checkQuizAnswer').onclick=checkQuiz;
document.querySelector('#nextQuizQuestion').onclick=nextLocalQuizQuestion;
function finishQuiz(){quizPlayer.hidden=true;quizResults.hidden=false;document.querySelector('#quizResultScore').textContent=`${quizPoints} out of ${generatedQuiz.length}`;const percent=Math.round(quizPoints/generatedQuiz.length*100);document.querySelector('#quizResultMessage').textContent=percent===100?'Excellent—every answer is correct!':percent>=80?'Great work! Review the questions below.':'Keep practicing and try the missed questions again.';document.querySelector('#quizReview').innerHTML=quizAnswers.map((item,index)=>`<div class="quiz-review-item ${item.correct?'':'missed'}"><span>${item.correct?'✓':'×'}</span><div><strong>${escapeQuizHtml(item.question)}</strong><small>Your answer: ${escapeQuizHtml(item.response)}</small></div><em>${item.correct?'Correct':`Answer: ${escapeQuizHtml(item.answer)}`}</em></div>`).join('');document.querySelector('#quizProgressBar').style.width='100%';window.scrollTo({top:0,behavior:'smooth'})}
document.querySelector('#retryQuiz').onclick=startQuiz;document.querySelector('#newQuiz').onclick=()=>{quizResults.hidden=true;quizBuilder.hidden=false;window.scrollTo({top:0,behavior:'smooth'})};document.querySelector('#editQuiz').onclick=editLocalQuiz;
document.querySelector('#printQuizResults').onclick=()=>{document.body.classList.add('print-quiz');window.print()};
window.addEventListener('afterprint',()=>document.body.classList.remove('print-quiz'));

function quizRows(){return rowsForLanguage(quizKeyboardLanguage)}
function quizExpected(){const item=currentQuiz();if(!item||quizKeyboardLanguage==='en'||!hasMyanmar(item.answer))return null;return mappingsForLanguage(quizKeyboardLanguage).find(mapping=>item.answer.startsWith(mapping.value,quizBuffer.length))||null}
function setQuizKeyboardLanguage(language){if(!['ksw','pwo','en'].includes(language)||quizLocked)return;quizKeyboardLanguage=language;const typed=document.querySelector('#quizTypedAnswer');if(typed)typed.lang=quizKeyboardTag(language);renderQuizKeyboard();typed?.focus()}
document.querySelectorAll('[data-quiz-keyboard]').forEach(button=>button.addEventListener('click',()=>setQuizKeyboardLanguage(button.dataset.quizKeyboard)));
function quizBackspace(){if(quizLocked||!quizBuffer)return;quizBuffer=quizBuffer.slice(0,previousTextBoundary(quizBuffer,quizBuffer.length));document.querySelector('#quizTypedAnswer').textContent=quizBuffer;renderQuizKeyboard()}
function addQuizCharacter(value){if(quizLocked||currentQuiz().mode!=='typing')return;quizBuffer+=value;document.querySelector('#quizTypedAnswer').textContent=quizBuffer;renderQuizKeyboard()}
function quizControl(label,action,active=false){const button=document.createElement('button');button.type='button';button.className='key wide';button.textContent=label;button.onclick=action;if(active)button.classList.add('expected');return button}
function renderQuizKeyboard(){
  const box=document.querySelector('#quizKeyboard'),toolbar=document.querySelector('#quizKeyboardToolbar');box.innerHTML='';
  const item=currentQuiz();if(!item||item.mode!=='typing'){box.hidden=true;if(toolbar)toolbar.hidden=true;return}
  box.hidden=false;if(toolbar){toolbar.hidden=false;toolbar.querySelectorAll('[data-quiz-keyboard]').forEach(button=>{const active=button.dataset.quizKeyboard===quizKeyboardLanguage;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));button.disabled=quizLocked})}
  const expected=quizExpected(),useShift=expected?.shift||false,mobile=phoneKeyboard(),layout=quizRows(),lastRow=layout.length-1;
  if(!mobile){
    renderUnifiedDesktopKeyboard(box,{language:quizKeyboardLanguage,shifted:useShift,expected,hintShift:useShift,onKey:value=>addQuizCharacter(value),onBackspace:quizBackspace,onEnter:()=>quizLocked?document.querySelector('#nextQuizQuestion').click():submitQuizAnswer()});
    return
  }
  box.classList.remove('real-keyboard');
  layout.forEach((row,rowIndex)=>{
    const line=document.createElement('div');line.className='key-row';
    if(rowIndex===lastRow)line.appendChild(quizControl('Shift',()=>{},useShift));
    row.forEach(([key,normal,shift])=>{const button=document.createElement('button');button.type='button';button.className='key';button.dataset.code=key;button.innerHTML=`<small>${key}</small>${useShift?shift:normal}`;if(expected?.key===key)button.classList.add('expected');button.onclick=()=>addQuizCharacter(useShift?shift:normal);line.appendChild(button)});
    if(rowIndex===lastRow)line.appendChild(quizControl('⌫',quizBackspace));box.appendChild(line)
  });
  const bottom=document.createElement('div');bottom.className='key-row phone-bottom-row';
  const space=quizControl('Space',()=>addQuizCharacter(' '),expected?.key==='Space');space.classList.add('space');bottom.appendChild(space);
  bottom.appendChild(quizControl('Enter',()=>quizLocked?document.querySelector('#nextQuizQuestion').click():submitQuizAnswer()));box.appendChild(bottom)
}
document.addEventListener('keydown' ,event=>{if(quizView.hidden||quizPlayer.hidden||currentQuiz()?.mode!=='typing'||event.ctrlKey||event.metaKey||event.altKey)return;if(event.key==='Enter'){event.preventDefault();quizLocked?document.querySelector('#nextQuizQuestion').click():submitQuizAnswer();return}if(quizLocked)return;if(event.key==='Backspace'){event.preventDefault();quizBackspace();return}if(quizKeyboardLanguage!=='en'){if(event.key==='Shift')return;const key=physicalKey(event),match=rowsForLanguage(quizKeyboardLanguage).flat().find(([mapped])=>mapped===key);if(match){event.preventDefault();addQuizCharacter(event.shiftKey?match[2]:match[1])}}else if(event.key.length===1){event.preventDefault();addQuizCharacter(event.key)}});
window.addEventListener('typinglanguagechange',()=>{const inClassroom=typeof quizClassRole!=='undefined'&&quizClassRole==='student'&&quizClassCode;if(!inClassroom&&!quizView.hidden&&generatedQuiz.length&&quizSourceMode==='pairs')generateQuestions();if(!quizPlayer.hidden)showQuizQuestion()});
generateQuestions();
